### ISSUE TITLE
Same identifier for REPLACEMENT_ITEM and CONSULTING_ITEM

### ISSUE THREAD

**Issue by amporto** [levinet/Proj5EPBVAT#2]
@ Line 21 in iCommissionCalculator.java

REPLACEMENT_ITEM and CONSULTING_ITEM share the same int identifier of 3. REPLACEMENT_ITEM needs a different identifier.

**Comment by amporto** [comment]
REPLACEMENT_ITEM is set to the int value of 2.

**Comment by levinet** [comment]
how did you determine the output for the calculate commissions? like where does 3.02 and 4.02 etc... I see the experienced has a different table of percentages in decimal but I'm confused... I hate how she never gives us a way to run the application

**Comment by amporto** [comment]
You have to refer to the project explanation she gave us.

My JUnit keeps testing items I have commented out. I’ve restarted, pushed the updates, etc. but nothing affects it.

**Comment by levinet** [comment]
your test case should be 40.02 not 4.02 and for the other asserts too... maybe that's why its failing

**Comment by amporto** [comment]
No that one isn’t failing. Those are correct. 3% of 100 is $3.00. Plus whatever else is accumulated. Hence the 0.02 from the basic item. I also fixed the bonus method as well. Everything I have is working and passing.

**Comment by levinet** [comment]
I got the test cases for experienced done but I can't pull or push. I hate github rn

**Comment by amporto** [comment]
If you can’t pull then your test cases must have failed, because I just made the change to calculateBonusCommission. Just send them to me then. Did you find any bugs?

**Comment by levinet** [comment]
I think in Bonus Commission there is one

for (SalesTransaction s : this.transactions) {
// If we have already met the threshold for sales, simply add the
// commission in.
if (netSales >= minimumSalesForBonusCommission) {
netSales += s.getTransactionAmount();
bonusCommission += s.getTransactionAmount()
- bonusCommissionRate;
  } else if ((netSales + s.getTransactionAmount()) >= minimumSalesForBonusCommission) {
  // We need to determine how much of this sale qualifies for
  // commission.
  double commissionableAmount = (netSales + s.getTransactionAmount())-minimumSalesForBonusCommission;
  bonusCommission += commissionableAmount \* bonusCommissionRate;
  } else {
  // No commission. Simply go on.
  netSales += s.getTransactionAmount();
  }

I think this part of the code is wrong... I need a bug fix so leave this one for me if it is one lol My test cases I had right under yours:

/**
- TJL
- This test case will test the commission for an Experienced employee
- before reaching a minimum sales total of $5000.00 (no commission)
  _/
  @Test
  public void testExperiencedBeforeMinimum(){
  CommissionCalculator eEmp = new CommissionCalculator("Tom", 1);
  //Add a basic sale at $1.00 (no commission)
  eEmp.addSale(0, 1.00);
  assertEquals(eEmp.calculateCommission(), 0, 0);
  //Add a sale of $4999.00 to test commission at exactly the minimum of $5000.00
  //(no commission, must be above $5000.00)
  eEmp.addSale(0, 4999.00);
  assertEquals(eEmp.calculateCommission(), 0, 0);
  }
  /_*
- TJL
- This test will calculate the commission for an Experienced employee after reaching
- minimum sales. The method will test commission percentages of a basic sales item,
- maintenance contract, replacement parts, and consulting services
  _/
  @Test
  public void testExperiencedAfterMinimum(){
  CommissionCalculator eEmp = new CommissionCalculator("Tom", 1);
  eEmp.addSale(0, 5000.00);
  //First ensure commission at $5001.00
  //This also test correct percentage rates for Basic Sales Item
  eEmp.addSale(0, 1.00);
  assertEquals(eEmp.calculateCommission(), 0.04,0);
  //Test correct percentage for maintenance contract
  eEmp.addSale(1, 100.00);
  assertEquals(eEmp.calculateCommission(), 6.04, 0);
  //Test correct percentage for replacement parts
  eEmp.addSale(2, 100.00);
  assertEquals(eEmp.calculateCommission(), 7.54, 0);
  //Test correct percentage for consulting services
  eEmp.addSale(3, 100.00);
  assertEquals(eEmp.calculateCommission(), 15.54, 0);
  //We should now ensure proper commission rates up until the bonus commission sales level
  //is reached, when the commission rate increases
  eEmp.addSale(0, 94699);
  assertEquals(eEmp.calculateCommission(),3803.50, 0);
  }
  /_*
- TJL
- This test will calculate the commission for an Experienced employee after
- meeting the bonus requirement of $100,000.
  */
  @Test
  public void testExperiencedWithBonus(){
  CommissionCalculator eEmp=new CommissionCalculator("Tom", 1);
  eEmp.addSale(0, 100000.00);
  assertEquals(eEmp.calculateCommission(), 3800.00, 0);
  //Now ensure the bonus commission at $100002.00
  eEmp.addSale(0, 100.00);
  assertEquals(eEmp.calculateBonusCommission(),3804.00,0 );
  }
  }

**Comment by amporto** [comment]
Yeah I just fixed that method. It was just a one-liner

**Comment by levinet** [comment]
did you leave any bugs for me to squish?? lol and what other test cases should we include...I can write a couple for the getTotalSales() method but what else is there to test? is equivalence partitioning and boundary analysis covered?

**Comment by amporto** [comment]
One thing that is not necessarily a bug but you can put in there (don’t have to change it, just leave it open), is that calculateCommission and calculateBonusCommission is done separately. Which is why yours failed, because at $100.00 past the $100,000 marker, the actual bonus commission is just $1.50. Not the regular commission plus bonus commission. It doesn’t add to the total commission value. There’s actually no method that calculates total commission

The only thing to test would be to ensure you cannot enter a negative value, but that’s really it. Then EP and BVA would be satisfied, we don’t necessarily need any code coverage minimums.

**Comment by levinet** [comment]
will I be able to submit an issue if I can't push and pull? and also how do you create a new task issue

**Comment by amporto** [comment]
Yeah you don’t have to push or pull for tasks. Just add the repository GitHub Issues and make sure you have the correct url. And when it asks if you want to create a query, select “yes”. Then you should be able to add a task by either right clicking or clicking the task button.
